apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: devx-helloworld-springboot-template
  title: DevX Spring Boot gRPC HelloWorld Service Template
  description: Create a simple microservice using gRPC and Spring Boot Java
  tags:
    - recommended
    - java
    - grpc
spec:
  owner: devx@example.com
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: devx-helloworld-springboot-template
      description:
        title: Description
        type: string
        description: Use as the basis for a new service.
      http_port:
        title: Port
        type: integer
        default: 8080
        description: The port to run the gRPC service on
