apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{cookiecutter.component_id}}
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
  name: {{cookiecutter.component_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.component_id}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{cookiecutter.component_id}}
        backstage.io/kubernetes-id: {{cookiecutter.component_id}}
    spec:
      containers:
      - image: {{cookiecutter.component_id}}:0.0.1-SNAPSHOT
        imagePullPolicy: Never
        name: {{cookiecutter.component_id}}
        resources: {}
        ports:
          - containerPort: 8080 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 5
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{cookiecutter.component_id}}
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
  name: {{cookiecutter.component_id}}
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{cookiecutter.component_id}}
  type: ClusterIP
status:
  loadBalancer: {}
